apiVersion: apps/v1 # API version
kind: Deployment # Deployment type
metadata: # We are going to deploy
  name: asgbuggy-deployment 
spec:
  replicas: 1 # replicas
  selector:
    matchLabels: #lables
      app: asgbuggy
  template:
    metadata:
      labels:
        app: asgbuggy
    spec:
      containers:
      - name: asgbuggy #name of container
        image: 022006208139.dkr.ecr.us-east-1.amazonaws.com/asg #docker image that we want to deploy
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 #container port - standard port of web application
# service type loadbalancer
#expose this application to the internet   
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: asgbuggy
    k8s-app: asgbuggy
  name: asgbuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: asgbuggy
